- name: Dotfiles setup
  hosts: localhost,myhosts
  vars:
    ansible_python_interpreter: auto_silent
  become: true
  roles:
    - { role: common, tags: ['common'] }
    - { role: desktop, tags: ['desktop'] }
