---
- name: Ensure dotfiles directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/dotfiles"
    state: directory
  become: false

- name: Ensure local bin directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
    mode: '0755'
  become: false

- name: Copy dotfiles directory (only changed files)
  ansible.builtin.synchronize:
    src: "{{ playbook_dir }}/dotfiles/"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/dotfiles/"
    delete: yes
    recursive: yes
    times: yes
    checksum: yes
    rsync_opts:
      - "--exclude=nvim/.config/nvim/lazy-lock.json"
  become: false
  register: dotfiles_sync

- name: Stow all packages
  ansible.builtin.shell:
    cmd: |
      cd "{{ lookup('env', 'HOME') }}/.local/share/dotfiles"
      for dir in */; do
        stow --verbose --restow --no-folding -t {{ lookup('env', 'HOME') }} "${dir%/}"
      done
  register: stow_result
  changed_when: "'LINK' in stow_result.stdout"
  become: false
