[[mgr.prepend_keymap]]
on = "s"
run = "shell -- mpv-shuffle %s"
desc = "mpv-shuffle current selected file(s)"

[[mgr.prepend_keymap]]
on = "S"
run = "shell -- mpv-slideshow %s"
desc = "mpv-slideshow current selected file(s)"
