set -g mouse on

set -g base-index 1
set -g renumber-windows on
set -g pane-base-index 1

set -s escape-time 10
set -g repeat-time 600

# use a sane prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# vi mode for scrolling
set -g mode-keys vi

# pane navigtion hjkl
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# pane navigation HL
bind -r H previous-window
bind -r L next-window

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line

# Mac
# set -s copy-command 'pbcopy'
# bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'

# Linux
set -s copy-command 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
